# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- group: Dev

pool:
  name: DevPool

steps:
- task: CmdLine@2
  inputs:
    script: |
      sonar-scanner \
        -Dsonar.projectKey=Defilan_aag_infoblox \
        -Dsonar.organization=$(sonarorg) \
        -Dsonar.sources=. \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=$(sonarlogin)